import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout';
import { GlobalStateProvider } from '@/context/GlobalState/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <GlobalStateProvider>
          <PrimaryLayout>{children}</PrimaryLayout>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
